[CmdletBinding()]
param(
    [ValidateSet('Audit', 'Verify')]
    [string]$Mode = 'Audit',

    [ValidateRange(1, 5)]
    [int]$Passes = 1,

    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',

    [string]$Output = 'artifacts/recovery'
)

$ErrorActionPreference = 'Stop'
$env:DOTNET_CLI_TELEMETRY_OPTOUT = '1'
$env:DOTNET_NOLOGO = '1'
$repoRoot = Split-Path -Parent $PSScriptRoot
$outputRoot = [IO.Path]::GetFullPath((Join-Path $repoRoot $Output))
$matrixPath = Join-Path $repoRoot 'docs/evidence/mvp/recovery-matrix.md'

# The nine failures the specification names, in the order it names them. A run that does not produce a
# row for every one of these is an incomplete run, not a passing one.
$expected = [ordered]@{
    'forced-shutdown'      = 'Cierre inesperado / Unexpected shutdown'
    'removed-drive'        = 'USB/NAS desconectado / USB or NAS disconnected'
    'access-denied'        = 'Acceso denegado / Access denied'
    'provider-unavailable' = 'TMDB caído o limitado / TMDB down or rate limited'
    'corrupt-file'         = 'Archivo corrupto / Corrupt file'
    'media-engine-failure' = 'Motor multimedia falla / Media engine fails'
    'damaged-database'     = 'Base dañada / Damaged database'
    'failed-migration'     = 'Migración falla / Migration fails'
    'rename-conflict'      = 'Conflicto de renombrado / Rename conflict'
}

Push-Location $repoRoot
try {
    $passResults = @()
    for ($pass = 1; $pass -le $Passes; $pass++) {
        $passRoot = Join-Path $outputRoot "pass-$pass"
        if (Test-Path -LiteralPath $passRoot) { Remove-Item -LiteralPath $passRoot -Recurse -Force }
        New-Item -ItemType Directory -Force -Path $passRoot | Out-Null
        $env:APSOLUTIONS_LOCALMEDIA_RECOVERY_RESULTS = $passRoot

        try {
            dotnet test (Join-Path $repoRoot 'tests/ApSolutions.LocalMedia.IntegrationTests') `
                -c $Configuration --no-build --no-restore `
                --settings (Join-Path $PSScriptRoot 'test.runsettings') `
                --filter 'Category=Recovery' `
                --logger "trx;LogFileName=recovery-pass-$pass.trx" `
                --results-directory $passRoot
            $testExitCode = $LASTEXITCODE
        }
        finally {
            Remove-Item Env:APSOLUTIONS_LOCALMEDIA_RECOVERY_RESULTS -ErrorAction SilentlyContinue
        }

        $rows = @(Get-ChildItem -LiteralPath $passRoot -Filter '*.json' -File |
            ForEach-Object { Get-Content -LiteralPath $_.FullName -Raw | ConvertFrom-Json })
        $missing = @($expected.Keys | Where-Object { $rows.caseId -notcontains $_ })
        $falseSuccess = @($rows | Where-Object {
            $_.outcome -notin @('Continued', 'Degraded', 'Recoverable', 'AbortedSafely')
        })

        $passResults += [pscustomobject]@{
            pass         = $pass
            testExitCode = $testExitCode
            rows         = $rows
            missing      = $missing
            falseSuccess = $falseSuccess
        }

        Write-Output ("Pass {0}: {1} row(s), {2} missing, exit {3}." -f
            $pass, $rows.Count, $missing.Count, $testExitCode)
    }

    $last = $passResults[-1]
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Matriz de recuperación / Recovery matrix')
    $lines.Add('')
    $lines.Add('<!-- Generado por eng/run-recovery.ps1; no editar a mano. -->')
    $lines.Add('<!-- Generated by eng/run-recovery.ps1; do not edit by hand. -->')
    $lines.Add('')
    $lines.Add(('- Pasadas / Passes: {0}' -f $Passes))
    $lines.Add(('- Configuración / Configuration: {0}' -f $Configuration))
    $lines.Add('')
    $lines.Add('| Fallo / Failure | Resultado / Outcome | Detalle / Detail |')
    $lines.Add('|---|---|---|')
    foreach ($caseId in $expected.Keys) {
        $row = $last.rows | Where-Object { $_.caseId -eq $caseId } | Select-Object -First 1
        if ($null -eq $row) {
            $lines.Add(('| {0} | **SIN FILA / NO ROW** | la pasada no produjo resultado / the pass produced no result |' -f $expected[$caseId]))
        }
        else {
            $lines.Add(('| {0} | `{1}` | {2} |' -f $expected[$caseId], $row.outcome, $row.detail))
        }
    }

    $lines.Add('')
    Set-Content -LiteralPath $matrixPath -Value $lines -Encoding utf8
    Write-Output "Recovery matrix: $matrixPath"

    if ($Mode -eq 'Audit') {
        Write-Output 'Audit mode: findings inventoried, nothing blocks.'
        exit 0
    }

    $problems = @()
    foreach ($result in $passResults) {
        if ($result.testExitCode -ne 0) { $problems += "Pass $($result.pass) had failing tests." }
        if ($result.missing.Count -gt 0) { $problems += "Pass $($result.pass) is missing: $($result.missing -join ', ')." }
        if ($result.falseSuccess.Count -gt 0) { $problems += "Pass $($result.pass) reported an outcome outside the four allowed words." }
    }

    if ($Passes -gt 1) {
        $signatures = $passResults | ForEach-Object {
            (($_.rows | Sort-Object caseId | ForEach-Object { "$($_.caseId)=$($_.outcome)" }) -join ';')
        }
        if (($signatures | Select-Object -Unique).Count -ne 1) {
            $problems += 'Passes disagreed with each other: the matrix is flaky.'
        }
    }

    if ($problems.Count -gt 0) {
        $problems | ForEach-Object { Write-Error $_ }
        exit 1
    }

    Write-Output ("Recovery Verify over {0} pass(es): {1} failures, all with an explicit outcome." -f
        $Passes, $last.rows.Count)
}
finally {
    Pop-Location
}
